---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "cicd-docker-dind"
  gather_facts: false
  tasks:

    - name: "Verify KUBERNETES"
      when: inv_install_kubernetes| default(false)
      block:
        - name: "Check docker-compose command response"
          register: output
          changed_when: output.rc != 0
          failed_when: output.rc != 0
          ansible.builtin.command: "docker -v"

        - name: "Check docker-compose command response"
          register: output
          changed_when: output.rc != 0
          failed_when: output.rc != 0
          ansible.builtin.command: "docker-compose -v"

        - name: "Check API HTTPS URL"
          register: result
          failed_when: result.status != 401
          when: inv_install_kubernetes_cluster__is_manager | default(false)
          ansible.builtin.uri:
            validate_certs: no
            url: "https://{{ inventory_hostname }}:6443/"
            method: "GET"
            status_code: [401]

        - name: "Check k3s kubectl get nodes command response"
          register: output
          failed_when: output.rc != 0
          when: inv_install_kubernetes_cluster__is_manager | default(false)
          ansible.builtin.command: "k3s kubectl get nodes"

        - name: "Checkkubectl get pods --all-namespaces command response"
          register: output
          failed_when: output.rc != 0
          when: inv_install_kubernetes_cluster__is_manager | default(false)
          ansible.builtin.command: "kubectl get pods --all-namespaces"

    - name: "Verify APACHE2"
      when: inv_install_apache | default(false)
      block:
        - name: "Get Apache2 service current state"
          register: install_apache__service_status
          failed_when: not install_apache__service_status.status.ActiveState == 'active'
          ansible.builtin.systemd:
            name: "apache2"

        - name: "Check Apache2 folders and conf"
          loop:
            - "/etc/apache2/apache2.conf"
            - "/etc/apache2/ports.conf"
          loop_control:
            loop_var: folder_path
          register: folder_check
          failed_when: not folder_check.stat.exists
          ansible.builtin.stat:
            path: "{{ folder_path }}"

        - name: "Check Apache2 HTTP connectivity"
          ansible.builtin.wait_for:
            host: "localhost"
            port: "{{ inv_install_apache__http_listen_port }}"
            timeout: 120

        - name: "Check Apache2 HTTPS connectivity"
          ansible.builtin.wait_for:
            host: "localhost"
            port: "{{ inv_install_apache__https_listen_port }}"
            timeout: 120

        - name: "Get Apache2 service current state"
          register: apache_service_status
          failed_when: not apache_service_status.status.ActiveState == 'active'
          ansible.builtin.systemd:
            name: "apache2"

        - name: "Check Apache2 default configuration"
          block:
            - name: "Check Apache2 folders and conf"
              loop:
                - "/etc/apache2/apache2.conf"
                - "/etc/apache2/ports.conf"
              loop_control:
                loop_var: folder_path
              register: folder_check
              failed_when: not folder_check.stat.exists
              ansible.builtin.stat:
                path: "{{ folder_path }}"

            - name: "Check Apache2 HTTP and conf"
              loop: "{{ inv_add_apache_confs__configurations }}"
              loop_control:
                loop_var: vhost
              register: folder_check
              failed_when: not folder_check.stat.exists
              ansible.builtin.stat:
                path: "{{ inv_add_apache_confs__conf_path }}/{{ vhost.server.name }}-HTTP.conf"

            - name: "Check Apache2 HTTPS and conf"
              loop: "{{ inv_add_apache_confs__configurations }}"
              loop_control:
                loop_var: vhost
              register: folder_check
              when: vhost.ssl
              failed_when: not folder_check.stat.exists
              ansible.builtin.stat:
                path: "{{ inv_add_apache_confs__conf_path }}/{{ vhost.server.name }}-HTTPS.conf"

            - name: "Check HTTPS conf: certs"
              loop: "{{ inv_add_apache_confs__configurations }}"
              loop_control:
                loop_var: vhost
              register: folder_check
              when: vhost.ssl.enabled | default(false)
              failed_when: not folder_check.stat.exists
              ansible.builtin.stat:
                path: "{{ vhost.ssl.crt }}"

            - name: "Check HTTPS conf: keys"
              loop: "{{ inv_add_apache_confs__configurations }}"
              loop_control:
                loop_var: vhost
              register: folder_check
              when: vhost.ssl.enabled | default(false)
              failed_when: not folder_check.stat.exists
              ansible.builtin.stat:
                path: "{{ vhost.ssl.key }}"

        - name: "Check Apache2 webserver"
          block:
            - name: "Check Apache2 connectivity"
              ansible.builtin.wait_for:
                host: "localhost"
                port: "{{ inv_add_apache_confs__http_listen_port }}"
                timeout: 120

            - name: "Check default vhost on HTTP"
              register: result
              failed_when: not (result.status == 503 or result.status == -1)
              ansible.builtin.uri:
                url: "http://localhost:{{ inv_add_apache_confs__http_listen_port }}/"
                method: "GET"

            - name: "Check default vhost on HTTPS"
              register: result
              failed_when: not (result.status == 503 or result.status == -1)
              ansible.builtin.uri:
                url: "https://localhost:{{ inv_add_apache_confs__https_listen_port }}/"
                method: "GET"
